
[server]
addr = "127.0.0.1"
port = "8081"

[server_monitor]
addr = "127.0.0.1"
port = "3781"

[raft]
addr = "127.0.0.1"
port = "12001"
peers = ["127.0.0.1:12001",  "127.0.0.1:12002",  "127.0.0.1:12000"]
peer_storage = "raft1/raft_peer_storage"
snapshot_storage = "raft1/raft_snapshot_storage"
store_backend = "leveldb"
storage_backend_path = "raft1/storage_backend_path"
raft_log_path = "raft1/raft_log_path"
apply_log_path = "raft1/apply_log_path"
enable_single_node = false

[rpc]
addr = "127.0.0.1"
port = "32124"

[log]

log_dir = "raft1/logs"
log_name = "raft_access_log"
log_level = "debug"
